version: 2
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/awesome_events"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          update_type: "all"
    version_requirement_updates: "off"