version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/awesome_events"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    versioning-strategy: "lockfile-only"
    ignore:
      - dependency-name: "rails"
        versions: [">= 6.1.0"]
      - dependency-name: "bundler"
        versions: [">= 2.4.0"]