# version: 2
# update_configs:
#   - package_manager: "ruby:bundler"
#     directory: "/awesome_events"
#     update_schedule: "weekly"
#     allowed_updates:
#       - match:
#           update_type: "all"
#     version_requirement_updates: "off"

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/awesome_events"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    versioning-strategy: "auto"