version: "3"
services:
  mysql:
    image: mysql:5.7
    command: ["--bind-address=0.0.0.0"]
    environment:
      MYSQL_ROOT_PASSWORD: password
    # portsの公開設定は動作させるだけなら必要ではないが、ホスト側からMYSQLに接続できるようにしておくと管理ツールが使いやすくなる
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_USERNAME: app
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/app
      - docker_app_bundle:/app/vendor/bundle
      - docker_app_node_modules:/app/node_modules

volumes:
  mysql-data:
    driver: local
  docker_app_bundle:
    driver: local
  docker_app_node_modules:
    driver: local